# Generated by Django 4.2.12 on 2024-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_alter_article_author_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default="içerik kısmı"),
            preserve_default=False,
        ),
    ]
