# Generated by Django 4.2.12 on 2024-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Makaleye fotoğraf ekleyin",
            ),
        ),
    ]
