# Generated by Django 5.0.6 on 2024-05-27 17:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0006_alter_article_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content2",
            field=tinymce.models.HTMLField(),
        ),
    ]
